name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-blog:$(date +"%Y-%m-%d")

    - name: docker login
      run: |
        docker login -u habtamu -p ${{ secrets.DOCKER_HUB_TOKEN }}
  
    - name: Publish the Docker image with the specified tag
      run: |
        docker image push -a habtamu/my-blog:2023-12-28
    
